<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Linked {client} account.' => '{client} привязан.',
    'Social network {client} has been successfully disabled.' => '{client} отвязан.',
    'Unable to link {client} account. There is another user using it.' => 'Не удалось привязать {client} так как это уже сделал другой пользователь.',
    'Unable to link {client} account: {errors}' => 'Не удалось привязать {client}: {errors}',
    'Unable to save user: {errors}' => 'Не удалось сохранить пользователя: {errors}',
    'Unable to save {client} account: {errors}' => 'Не удалось сохранить аккаунт {client}: {errors}',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Пользователь с таким же email как в {client} уже существует, но не привязан. Залогиньтесь при помощи email чтобы это исправить.',
];
