<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => 'Создан',
    'Created By' => 'Автор',
    'ID' => 'ID',
    'Status' => 'Статус',
    'Updated At' => 'Обновлён',
    'User contributed notes' => 'Комментарии пользователей',
    'at {time}' => 'в {time}',
    'Leave a comment' => 'Оставить комментарий',
    'Comment' => 'Комментировать',
    '{loginLink} or {signupLink} to post comments.' => '{loginLink} или {signupLink}, чтобы комментировать.',
    'Login' => 'Войти',
    'signup' => 'зарегистрироваться',
    'Text' => 'Комментарий',
    'Delete' => 'Удалить',
    'Are you sure you want to delete this comment?' => 'Вы уверены, что хотите удалить этот комментарий?',
    'Comment deleted.' => 'Комментарий удален.',
    'Failed to delete comment.' => 'Ошибка при удалении комментария.',
    'You can not delete this comment.' => 'Вы не можете удалить этот комментарий.',
];
