<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View  {n, plural, one{one more project} other{# more projects}}' => 'Ещё {n, plural, one{# проект} few{# проекта} many{# проектов} other{# проектов}}',
    'Add project' => 'Добавить проект',
    'After the image upload, you will be able to crop it.' => 'Вы сможете кадрировать изображение после его загрузки.',
    'Any Yii verison' => 'Любая версия Yii',
    'Any code access' => 'Код не важен',
    'Apply' => 'Применить',
    'Approve' => 'Одобрить',
    'Are you sure you want to delete this image?' => 'Вы уверены что хотите удалить это изображение?',
    'Back' => 'Назад',
    'Cancel' => 'Отменить',
    'Content' => 'Содержимое',
    'Created At' => 'Создан',
    'Created By' => 'Автор',
    'Delete image' => 'Удалить скриншот',
    'Deleted' => 'Удалён',
    'Description in {language}' => 'Описание на {language, select, Русский{русском} other{языке {language}}}',
    'Draft' => 'Черновик',
    'Featured projects' => 'Выбор редакции',
    'Filters' => 'Фильтры',
    'General' => 'Общая информация',
    'General info' => 'Общая информация',
    'ID' => 'ID',
    'Is Featured' => 'Выбор редакции',
    'Is OpenSource' => 'Является OpenSource',
    'Language' => 'Язык',
    'Made one? Share it!' => 'Сделал проект? Добавь!',
    'Manage projects' => 'Управление проектами',
    'New projects' => 'Новые проекты',
    'Next' => 'Далее',
    'Not open source' => 'Закрытый код',
    'Only Featured' => 'Только выбор редакции',
    'Open source' => 'Открытый код',
    'OpenSource' => 'Открытый код',
    'Please, upload some screenshots to make your project look nice.' => 'Загрузите несколько скриншотов.',
    'Preview & Approve' => 'Предпросмотр и публикация',
    'Project ID' => 'ID проекта',
    'Project added!' => 'Проект добавлен!',
    'Projects' => 'Проекты',
    'Projects built with Yii' => 'Проекты, созданные с использованием Yii',
    'Publish' => 'Опубликовать',
    'Published' => 'Опубликован',
    'Re-crop image' => 'Кадрировать скриншот',
    'Save as draft' => 'В черновики',
    'Screenshots' => 'Скриншоты',
    'Slug' => 'Slug',
    'Source Code' => 'Исходный код',
    'Source URL' => 'Исходный код',
    'Status' => 'Статус',
    'Tag ID' => 'ID тега',
    'Tags' => 'Теги',
    'Title' => 'Название',
    'URL' => 'URL',
    'Unknown' => 'Неизвестен',
    'Update' => 'Редактировать',
    'Update project {title}' => 'Редактировать проект {title}',
    'Updated At' => 'Обновлён',
    'Updated By' => 'Обновил',
    'Updated: ' => 'Обновлено:',
    'Upload' => 'Загрузить',
    'Upload an image' => 'Загрзуить скриншот',
    'Upload screenshots' => 'Загрузить скриншоты',
    'User ID' => 'ID пользователя',
    'Yii Version' => 'Версия Yii',
    'You can not update this project.' => 'Вы не можете редактировать этот проект.',
    'You can upload up to 5 images. The first image will be used as a main preview of your project, while others will be displayed on the project details page' => 'Можно загрузить до пяти изображений. Первое изображение используется в карточке проекта, остальные можно посмотреть на странице проекта.',
    'You have no bookmarked projects yet.' => 'В ваших закладках пока нет проектов.',
    '{n, plural, one{# project} other{# projects}} made with {link}' => '{n,plural,one{# проект} few{# проекта} many{# проектов} other{# проектов}} сделано на {link}',
];
