<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this image?' => 'Вы уверены что хотите удалить это изображение?',
    'Tags' => 'Теги',
    'Updated: ' => 'Обновлено:',
    'Add project' => 'Добавить проект',
    'Any Verison' => 'Любая версия',
    'Apply' => 'Применить',
    'Content' => 'Содержимое',
    'Created At' => 'Создан',
    'Created By' => 'Автор',
    'Deleted' => 'Удалён',
    'Description in {language}' => 'Описание на языке "{language}"',
    'Does not matter' => 'Не важно',
    'Draft' => 'Черновик',
    'Featured projects' => 'Выбор редакции',
    'ID' => 'ID',
    'Is Featured' => 'Выбор редакции',
    'Is OpenSource' => 'OpenSource',
    'Language' => 'Язык',
    'Manage projects' => 'Управление проектами',
    'More projects' => 'Ещё проекты',
    'New projects' => 'Новые проекты',
    'No' => 'Нет',
    'Only Featured' => 'Только выбор редакции',
    'OpenSource' => 'Открытый код',
    'Project ID' => 'ID проекта',
    'Project added!' => 'Проект добавлен!',
    'Projects' => 'Проекты',
    'Projects built with Yii' => 'Проекты, созданные с использованием Yii',
    'Published' => 'Опубликован',
    'Save' => 'Сохранить',
    'Slug' => 'Slug',
    'Source Code: ' => 'Исходный код:',
    'Source URL' => 'Исходный код',
    'Status' => 'Статус',
    'Tag ID' => 'ID тега',
    'Title' => 'Название',
    'URL' => 'URL',
    'Unknown' => 'Неизвестен',
    'Update' => 'Редактировать',
    'Update project {title}' => 'Редактировать проект {title}',
    'Updated At' => 'Обновлён',
    'Updated By' => 'Обновил',
    'Upload' => 'Загрузить',
    'User ID' => 'ID пользователя',
    'Yes' => 'Да',
    'Yii Version' => 'Версия Yii',
    'You can not update this project.' => 'Вы не можете редактировать этот проект.',
];
