<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Удаляем?',
    'Auth Key' => 'Ключ авторизации',
    'Created At' => 'Создан',
    'Password Hash' => 'Хеш пароля',
    'Password Reset Token' => 'Токен восстановления пароля',
    'Updated At' => 'Обновлён',
    'You haven\'t added any projects yet.' => 'Вы ещё не добавили ни одного проекта.',
    'Active' => 'Активен',
    'Create' => 'Создать',
    'Delete' => 'Удалить',
    'Email' => 'Почта',
    'Facebook' => 'Facebook',
    'Fullname' => 'Полное имя',
    'Github' => 'Github',
    'ID' => 'ID',
    'Status' => 'Статус',
    'Twitter' => 'Twitter',
    'Update' => 'Редактровать',
    'Update {modelClass}: ' => 'Редактиовать {modelClass}: ',
    'Username' => 'Ник',
    'Users' => 'Пользователи',
];
