<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update user {username}: ' => 'Профиль {username}:',
    'Active' => 'Активен',
    'Are you sure you want to delete this item?' => 'Удаляем?',
    'Auth Key' => 'Ключ авторизации',
    'Avatar' => 'Аватар',
    'Can not save your profile.' => ' Не удалось обновить ваш профиль.',
    'Connect with {servicename}' => 'Привязать {servicename}',
    'Create' => 'Создать',
    'Created At' => 'Создан',
    'Current avatar' => 'Текущий аватар',
    'Delete' => 'Удалить',
    'Email' => 'Почта',
    'Facebook' => 'Facebook',
    'Fullname' => 'Полное имя',
    'Github' => 'Github',
    'Haven\'t added any projects yet.' => 'Пока нет добавленных проектов.',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Неправильный логин или пароль.',
    'Manage users' => 'Управление пользователями',
    'Password Hash' => 'Хеш пароля',
    'Password Reset Token' => 'Токен восстановления пароля',
    'Status' => 'Статус',
    'Twitter' => 'Twitter',
    'Update' => 'Редактировать',
    'Updated At' => 'Обновлён',
    'Username' => 'Ник',
    'Users' => 'Пользователи',
    'You can not update this user.' => 'Вы не можете редактировать этого пользователя.',
    'Your profile has been successfully updated.' => 'Ваш профиль успешно обновлён.',
];
