<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Explore projects' => 'Explorer les projets',
    'Logout' => 'Déconnexion',
    'About' => 'A propos',
    'Bookmarks' => 'Favoris',
    'Don\'t have an account? {signUpLink}' => 'Pas de compte ? {signUpLink}',
    'Email' => 'Email',
    'If you forgot your password you can {reset_it}.' => 'Si vous avez perdu votre mot de passe, vous pouvez {reset_it}.',
    'Linked {client} account.' => 'Compte {client} lié.',
    'Login' => 'Connexion',
    'Password' => 'Mot de passe',
    'Please choose your new password:' => 'Choisissez votre nouveau mot de passe:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Remplissez votre email, un lien pour réinitialiser votre mot de passe vous y sera envoyé.',
    'RSS feed' => 'Flux RSS',
    'Request password reset' => 'Demander une réinitialisation de mot de passe',
    'Reset password' => 'Réinitialiser le mot de passe',
    'Save' => 'Enregister',
    'Send' => 'Envoyer',
    'Sign in with {service}' => 'Se connecter avec {service}',
    'Sign up!' => 'Créez-le !',
    'Signup' => 'Création de compte',
    'Social network {client} has been successfully disabled.' => 'Le réseau {client} a bien été désactivé.',
    'This email address has already been taken.' => 'Cette adresse email est déjà utilisée.',
    'This username has already been taken.' => 'Ce nom d\'utilisateur est déjà utilisé.',
    'Unable to link {client} account. There is another user using it.' => 'Impossible de relier le compte {client}. Un autre utilisateur l\'utilise déjà.',
    'Unable to link {client} account: {errors}' => 'Impossible de relier le compte {client}: {errors}',
    'Unable to save user: {errors}' => 'Impossible d\'enregister l\'utilisateur {client}: {errors}',
    'Unable to save {client} account: {errors}' => 'Impossible de sauvegarder le compte {client}: {errors}',
    'Unknown' => 'Inconnu',
    'User name' => 'Nom d\'utilisateur',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Un utilisateur avec le même email que le compte {client} existe déjà mais n\'est pas relié. Connectez-vous avec votre e-mail d\'abord pour le relier.',
    'Username' => 'Nom d\'utilisateur',
    'or' => 'ou',
    'reset it' => 'le résillier',
];
