<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Any Status' => 'N\'importe quel statut',
    'Are you sure you want to delete this project?' => 'Etes-vous certain de vouloir supprimer ce projet ?',
    'Delete' => 'Supprimer',
    'Failed to delete project.' => 'Impossible de supprimer le projet.',
    'Failed to update project.' => 'Impossible de mettre à jour le projet.',
    'Project deleted.' => 'Projet supprimé.',
    'The project has been moved to draft.' => 'Ce projet a été déplacé dans les brouillons.',
    'You can not delete this project.' => 'Vous ne pouvez pas supprimer ce projet.',
    'You can not restore a deleted project.' => 'Vous ne pouvez pas restaurer un projet supprimé.',
    'You can only delete a project from a draft.' => 'Vous pouvez uniquement supprimer un projet en brouillon.',
    'Add project' => 'Ajouter un projet',
    'After the image upload, you will be able to crop it.' => 'Après le téléchargement de l\'image, vous pourrez la recadrer.',
    'Any Yii version' => 'N\'importe quelle version de Yii',
    'Any code access' => 'N\'importe quel accès au code',
    'Apply' => 'Appliquer',
    'Approve' => 'Valider',
    'Are you sure you want to delete this image?' => 'Etes-vous certain de vouloir supprimer cette image ?',
    'Back' => 'Retour',
    'Cancel' => 'Annuler',
    'Content' => 'Contenu',
    'Created At' => 'Créé le',
    'Created By' => 'Créé par',
    'Delete image' => 'Supprimer l\'image',
    'Deleted' => 'Supprimé',
    'Description in {language}' => 'Description en {language}',
    'Draft' => 'Brouillon',
    'Featured projects' => 'Projets à la une',
    'Filters' => 'Filtres',
    'General' => 'Général',
    'General info' => 'Informations générales',
    'ID' => 'ID',
    'Is Featured' => 'ID à la une',
    'Is OpenSource' => 'OpenSource',
    'Language' => 'Langue',
    'Made one? Share it!' => 'Vous en avez fait un ? Partagez-le !',
    'Manage projects' => 'Gérer les projets',
    'Mark as primary image' => 'Choisir comme image principale',
    'New projects' => 'Nouveaux projets',
    'Next' => 'Suivant',
    'Not open source' => 'Non open source',
    'Only Featured' => 'A la une uniquement',
    'Open source' => 'Open source',
    'OpenSource' => 'Open source',
    'Please, upload some screenshots to make your project look nice.' => 'Merci de télécharger quelques captures d\‘écrans afin de rendre la fiche de votre projet joli.',
    'Preview & Approve' => 'Prévisualiser et valider',
    'Primary image' => 'Image principale',
    'Project ID' => 'ID projet',
    'Project added!' => 'Projet ajouté !',
    'Projects' => 'Projets',
    'Projects built with Yii' => 'Projets faits avec Yii',
    'Publish' => 'Publier',
    'Published' => 'Publié',
    'Re-crop image' => 'Recadrer cette image',
    'Save as draft' => 'Passer en brouillon',
    'Screenshots' => 'Captures d\'écran',
    'Slug' => 'Slug',
    'Source Code' => 'Code source',
    'Source URL' => 'Url source',
    'Status' => 'Statut',
    'Tag ID' => 'ID étiquette',
    'Tags' => 'Etiquettes',
    'Title' => 'Titre',
    'Top {n}' => 'Top {n}',
    'Top {n} projects is still empty' => 'Le top {n} des projets est encore vide',
    'URL' => 'URL',
    'Unknown' => 'Inconnu',
    'Update' => 'Mise à jour',
    'Update project {title}' => 'Mise à jour du projet {title}',
    'Updated At' => 'Mis à jour le',
    'Updated By' => 'Mis à jour par',
    'Updated: ' => 'Mis à jour :',
    'Upload' => 'Téléchargement',
    'Upload an image' => 'Télécharger une image',
    'Upload screenshots' => 'Télécharger des captures d\'écran',
    'User ID' => 'ID utilisateur',
    'View  {n, plural, one{one more project} other{# more projects}}' => 'Voir {n, plural, one{un projet de plus} other{# projets de plus}}',
    'Yii Version' => 'Version de Yii',
    'You can not update this project.' => 'Vous ne pouvez pas mettre à jour ce projet',
    'You can upload up to 5 images. The first image will be used as a main preview of your project, while others will be displayed on the project details page' => 'Vous pouvez télécharger jusqu\'à 5 images. La première sera utilisée comme aperçu principal de votre projet, les autres seront affichées dans la fiche de votre projet',
    'You have no bookmarked projects yet.' => 'Vous n\'avez pas encore mis de projets en favoris.',
    '{n, plural, one{# project} other{# projects}} made with {link}' => '{n,plural,one{# projet fait} other{# projets faits}} avec {link}',
];
