<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avatar' => 'Avatar',
    'Can not save your profile.' => 'Impossible de sauvegarder votre profil.',
    'Current avatar' => 'Avatar actuel',
    'Update user {username}: ' => 'Edition de l\'utilisateur {username} :',
    'You can not update this user.' => 'Vous ne pouvez pas éditer cet utilisateur.',
    'Your profile has been successfully updated.' => 'Votre profil a bien été mis à jour.',
    'Active' => 'Actif',
    'Are you sure you want to delete this item?' => 'Etes vous certain de vouloir supprimer cet élément ?',
    'Auth Key' => 'Clef d\'auth',
    'Connect with {servicename}' => 'Se connecter avec {servicename}',
    'Create' => 'Créer',
    'Created At' => 'Créé le',
    'Delete' => 'Supprimer',
    'Email' => 'Email',
    'Facebook' => 'Facebook',
    'Fullname' => 'Nom complet',
    'Github' => 'Github',
    'Haven\'t added any projects yet.' => 'N\'a encore ajouté aucun projet.',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Nom d\'utilisateur ou mot de passe erroné.',
    'Manage users' => 'Gérer les utilisateurs',
    'Password Hash' => 'Hash de mot de passe',
    'Password Reset Token' => 'Token de RAZ mot de passe',
    'Status' => 'Status',
    'Twitter' => 'Twitter',
    'Update' => 'Mettre à jour',
    'Updated At' => 'Mis à jour le',
    'Username' => 'Nom d\'utilisateur',
    'Users' => 'Utilisateurs',
];
