<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Explore projects' => 'Projekte entdecken',
    'Logout' => 'Ausloggen',
    'About' => 'Über',
    'Bookmarks' => 'Lesezeichen',
    'Don\'t have an account? {signUpLink}' => 'Noch kein Konto? {signUpLink}',
    'Email' => 'E-Mail',
    'If you forgot your password you can {reset_it}.' => 'Wenn du dein Passwort vergessen hast kannst du es {reset_it}.',
    'Linked {client} account.' => 'Verlinktes {client} Konto.',
    'Login' => 'Einloggen',
    'Password' => 'Passwort',
    'Please choose your new password:' => 'Bitte wähle ein neues Passwort:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Bitte gebe deine E-Mail-Adresse an, ein Link zum zurücksetzen des Passwort wird dir zugesendet.',
    'RSS feed' => 'RSS',
    'Request password reset' => 'Passwort zurücksetzen anfrage',
    'Reset password' => 'Passwort zurücksetzen',
    'Save' => 'Speichern',
    'Send' => 'Senden',
    'Sign in with {service}' => 'Einloggen mit {service}',
    'Sign up!' => 'Jetzt registrieren!',
    'Signup' => 'Regisitrieren',
    'Social network {client} has been successfully disabled.' => 'Die Verbindung zu {client} wurde erfolgreich deaktiviert.',
    'This email address has already been taken.' => 'Diese E-Mail-Adresse wird bereits verwendet.',
    'This username has already been taken.' => 'Dieser Benutzername wird bereits verwendet.',
    'Unable to link {client} account. There is another user using it.' => 'Du kannst dich mit {client} nicht verbinden. Eine andere Person verwendet dies bereits.',
    'Unable to link {client} account: {errors}' => 'Du kannst dich mit {client} nicht verbinden: {errors}',
    'Unable to save user: {errors}' => 'Fehler beim speichern des Kontos: {errors}',
    'Unable to save {client} account: {errors}' => 'Fehler beim speichern des {client} Kontos: {errors}',
    'Unknown' => 'Unbekannt',
    'User name' => 'Benutzername', // same..
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Ein Benutzer mit der gleichen E-Mail-Adresse als im {client} Konto existiert bereits aber ist nicht diesem verbunden. Logge dich zuerst mit der E-Mail-Adresse ein um dich damit zu Verbinden.',
    'Username' => 'Benutzername', // same...
    'or' => 'order',
    'reset it' => 'zurücksetzen',
];
