<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Any Status' => 'Jeder Status',
    'Are you sure you want to delete this project?' => 'Bist du sicher das du dieses Projekt löschen möchtest?',
    'Delete' => 'Löschen',
    'Failed to delete project.' => 'Fehler beim löschen des Projekts.',
    'Failed to update project.' => 'Fehler beim aktualisieren des Projekts',
    'Project deleted.' => 'Projekt löschen.',
    'The project has been moved to draft.' => 'Das Projekt wurde zu den Entwürfen verschoben.',
    'You can not delete this project.' => 'Du kannst dieses Projekt nicht löschen.',
    'You can not restore a deleted project.' => 'Du kannst ein gelöschtes Projekt nicht wieder herstellen.',
    'You can only delete a project from a draft.' => 'Du kannst ein Projekt nur vom Draft löschen.',
    'Add project' => 'Projekte hinzufügen',
    'After the image upload, you will be able to crop it.' => 'Nach dem hochladen des Bildes kannst du es beschneiden.',
    'Any Yii version' => 'Alle Yii Versionen',
    'Any code access' => 'Alles Zugriffs codes',
    'Apply' => 'Anwenden',
    'Approve' => 'Prüfen',
    'Are you sure you want to delete this image?' => 'Bist du sicher das du diese Projekt löschen möchtest?',
    'Back' => 'Zurück',
    'Cancel' => 'Abbrechen',
    'Content' => 'Verbinden',
    'Created At' => 'Erstellt am',
    'Created By' => 'Erstellt von',
    'Delete image' => 'Bild löschen',
    'Deleted' => 'Löschen',
    'Description in {language}' => 'Beschreibung in {language}',
    'Draft' => 'Entwurf',
    'Featured projects' => 'Hervorgehobene Projekte',
    'Filters' => 'Filter',
    'General' => 'Allgemein',
    'General info' => 'Allgemeine Infos',
    'ID' => 'ID',
    'Is Featured' => 'Ist hervorgehoben',
    'Is OpenSource' => 'Ist Open Source', // <-- open source written different
    'Language' => 'Sprache',
    'Made one? Share it!' => 'Ein Projekt gemacht? Teile es mit uns!',
    'Manage projects' => 'Projekte verwalten',
    'Mark as primary image' => 'Als Anzeigebild markieren',
    'New projects' => 'Neue Projekte',
    'Next' => 'Nächstes',
    'Not open source' => 'Nicht Open Source', // <-- open source written different
    'Only Featured' => 'Nur hervorgehobene',
    'Open source' => 'Open Source', // same .. // <-- open source written different
    'OpenSource' => 'Open Source', // same ...  // <-- open source written different
    'Please, upload some screenshots to make your project look nice.' => 'Bitte lade eine paar Screenshots hoch damit das Projekt gut aussieht.',
    'Preview & Approve' => 'Vorschau & Speichern',
    'Primary image' => 'Anzeigebild',
    'Project ID' => 'Projekt ID',
    'Project added!' => 'Projekt wurde hinzugefügt',
    'Projects' => 'Projekte',
    'Projects built with Yii' => 'Projekte mit Yii realisiert',
    'Publish' => 'Veröffentlichen',
    'Published' => 'Veröffentlicht',
    'Re-crop image' => 'Bild neu zuschneiden',
    'Save as draft' => 'Als Entwurf speichern',
    'Screenshots' => 'Screenshots',
    'Slug' => 'Adresse Pfadsegment', // maybe the best translation for slug ... 
    'Source Code' => 'Quellcode',
    'Source URL' => 'Quellen Adresse',
    'Status' => 'Status',
    'Tag ID' => 'Tag ID',
    'Tags' => 'Tags',
    'Title' => 'Titel',
    'Top {n}' => 'Top {n}',
    'Top {n} projects is still empty' => 'Top {n} ist leer.',
    'URL' => 'Adresse',
    'Unknown' => 'Unbekannt',
    'Update' => 'Aktualisiert',
    'Update project {title}' => 'Projekt {title} aktualisieren',
    'Updated At' => 'Aktualisiert am',
    'Updated By' => 'Aktualisiert von',
    'Updated: ' => 'Aktualisiert:',
    'Upload' => 'Hochladen',
    'Upload an image' => 'Bild hochladen',
    'Upload screenshots' => 'Screenshot hochladen',
    'User ID' => 'Benutzer ID',
    'View  {n, plural, one{one more project} other{# more projects}}' => 'Zeige {n, plural, one{ein Projekt} other{# mehrere Projekte}}',
    'Yii Version' => 'Yii Version',
    'You can not update this project.' => 'Du kannst dieses Projekt nicht aktualisieren.',
    'You can upload up to 5 images. The first image will be used as a main preview of your project, while others will be displayed on the project details page' => 'Du kannst 5 Bilder hochladen. Das erste Bild wird als Vorschau bild des Projekts verwendet. Die andere Bildern werden auf der Projekt Detail Seite angezeigt',
    'You have no bookmarked projects yet.' => 'Du hast keine markierten Projekte.',
    '{n, plural, one{# project} other{# projects}} made with {link}' => '{n,plural,one{# Projekt} other{# Projekte}} mit {link} gemacht',
];
