<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avatar' => 'Benutzerbild',
    'Can not save your profile.' => 'Dein Konto wurde nicht gespeichert.',
    'Current avatar' => 'Aktuelles Benutzerbild',
    'Update user {username}: ' => 'Benutzer {username} aktualisieren:',
    'You can not update this user.' => 'Dieser Benutzer kann nicht aktualisiert werden.',
    'Your profile has been successfully updated.' => 'Dein Profil wurde erfolgreich aktualisiert.',
    'Active' => 'Aktiv',
    'Are you sure you want to delete this item?' => 'Bist du sicher das du dieses Element löschen möchtest?',
    'Auth Key' => 'Authentifizierungs Schlüssel',
    'Connect with {servicename}' => 'Mit {servicename} verbinden',
    'Create' => 'Erstellt',
    'Created At' => 'Erstellt am',
    'Delete' => 'Löschen',
    'Email' => 'E-Mail',
    'Facebook' => 'Facebook',
    'Fullname' => 'Name',
    'Github' => 'Github',
    'Haven\'t added any projects yet.' => 'Es wurden noch keine Projekte hinzugefügt.',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Benutzername oder Passwort ist nicht gültig.',
    'Manage users' => 'Benutzer bearbeiten',
    'Password Hash' => 'Passwort Hash',
    'Password Reset Token' => 'Passwort zurücksetzen Token',
    'Status' => 'Status',
    'Twitter' => 'Twitter',
    'Update' => 'Anpassen',
    'Updated At' => 'Aktualisiert am',
    'Username' => 'Benutzername',
    'Users' => 'Benutzer',
];
