<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Explore projects' => 'Khám phá dự án',
    'Logout' => 'Đăng xuất',
    'About' => 'Về dự án',
    'Bookmarks' => 'Đánh dấu',
    'Don\'t have an account? {signUpLink}' => 'Chưa có tài khoản? {signUpLink}',
    'Email' => 'Email',
    'If you forgot your password you can {reset_it}.' => 'Nếu bạn quên mật khẩu, khôi phục mật khẩu {reset_it}.',
    'Linked {client} account.' => 'Liên kết tài khoản {client}.',
    'Login' => 'Đăng nhập',
    'Password' => 'Mật khẩu',
    'Please choose your new password:' => 'Chọn mật khẩu mới:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Vui lòng nhập địa chỉ email. Liên kết thay đổi mật khẩu sẽ gửi vào địa chỉ email.',
    'RSS feed' => 'RSS',
    'Request password reset' => 'Yêu cầu thay đổi mật khẩu',
    'Reset password' => 'Khôi phục mật khẩu',
    'Save' => 'Lưu',
    'Send' => 'Gửi',
    'Sign in with {service}' => 'Đăng ký với {service}',
    'Sign up!' => 'Đăng ký!',
    'Signup' => 'Đăng ký',
    'Social network {client} has been successfully disabled.' => 'Liên kết {client} đã được gỡ bỏ.',
    'This email address has already been taken.' => 'Địa chỉ email đã tồn tại.',
    'This username has already been taken.' => 'Tên đăng nhập đã tồn tại.',
    'Unable to link {client} account. There is another user using it.' => 'Không liên kết được {client} Thành viên đã được sử dung.',
    'Unable to link {client} account: {errors}' => 'Không liên kết được {client}: {errors}',
    'Unable to save user: {errors}' => 'Không lưu được thành viên: {errors}',
    'Unable to save {client} account: {errors}' => 'Không lưu được tài khoản {client}: {errors}',
    'Unknown' => 'Không rõ',
    'User name' => 'Tên đăng nhập',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Tên cùng với email của tài khoản {client} đã tồn tại, chưa được liên kết. Đăng nhập cùng với địa chỉ email để liên kết với tài khoản.',
    'Username' => 'Tên đăng nhập',
    'or' => 'hoặc',
    'reset it' => 'khôi phục',
];
