<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => 'Tạo lúc',
    'Created By' => 'Tạo bởi',
    'ID' => 'ID',
    'Status' => 'Trạng thái',
    'Updated At' => 'Cập nhật lúc',
    'User contributed notes' => 'Bình luận dự án',
    'at {time}' => 'в {time}',
    'Leave a comment' => 'Thêm bình luận',
    'Comment' => 'Bình luận',
    '{loginLink} or {signupLink} to post comments.' => '{loginLink} hoặc {signupLink}, để bình luận.',
    'Login' => 'Đăng nhập',
    'signup' => 'Đăng ký',
    'Text' => 'Nội dung',
    'Delete' => 'Xóa',
    'Are you sure you want to delete this comment?' => 'Xác nhận xóa?',
    'Comment deleted.' => 'Đã xóa bình luận.',
    'Failed to delete comment.' => 'Xóa bình luận không thành công.',
    'You can not delete this comment.' => 'Bạn không có quyền xóa bình luận.',
];
