<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Any Status' => 'Tất cả trạng thái',
    'Add project' => 'Thêm dự án',
    'After the image upload, you will be able to crop it.' => 'Sau khi ảnh được tải lên, bạn mới có thể thực hiện cắt ảnh .',
    'Any Yii version' => 'Tất cả phiên bản của Yii',
    'Any code access' => 'Dự án nguồn mở',
    'Apply' => 'Xác nhận',
    'Approve' => 'Chấp nhận',
    'Are you sure you want to delete this image?' => 'Xác nhận xóa hình ảnh?',
    'Are you sure you want to delete this project?' => 'Xác nhận xóa dự án?',
    'Back' => 'Quay lại',
    'Cancel' => 'Hủy',
    'Content' => 'Nội dung',
    'Created At' => 'Tạo lúc',
    'Created By' => 'Cập nhật lúc',
    'Delete' => 'Xóa',
    'Delete image' => 'Xóa ảnh',
    'Deleted' => 'Đã xóa',
    'Description in {language}' => 'Thông tin mô tả  {language, select, Русский{русском} other{ngôn ngữ {language}}}',
    'Draft' => 'Nháp',
    'Failed to delete project.' => 'Xóa dự án không thành công.',
    'Failed to update project.' => 'Cập nhật dự án không thành công.',
    'Featured projects' => 'Dự án nổi bật',
    'Filters' => 'Lọc',
    'General' => 'Tổng quan',
    'General info' => 'Thông tin tổng quan',
    'ID' => 'ID',
    'Is Featured' => 'Dự án nổi bật',
    'Is OpenSource' => 'Là mã nguồn mở',
    'Language' => 'Ngôn ngữ',
    'Made one? Share it!' => 'Bạn có dự án? Cùng chia sẻ!',
    'Manage projects' => 'Quản lý dự án',
    'Mark as primary image' => 'Chọn là ảnh chính',
    'New projects' => 'Dự án mới',
    'Next' => 'Tiếp theo',
    'Not open source' => 'Không phải mã nguồn mở',
    'Only Featured' => 'Chỉ là nổi bật',
    'Open source' => 'Mã nguồn mở',
    'OpenSource' => 'Mã nguồn mở',
    'Please, upload some screenshots to make your project look nice.' => 'Vui lòng tải lên một số ảnh của dự án để tham khảo.',
    'Preview & Approve' => 'Xem & chấp nhận',
    'Primary image' => 'Ảnh chính',
    'Project ID' => 'ID Dự án',
    'Project added!' => 'Đã thêm dữ án!',
    'Project deleted.' => 'Đã xóa dự án.',
    'Projects' => 'Danh sách dự án',
    'Projects built with Yii' => 'Các dự án được xây dựng trên Yii',
    'Publish' => 'Xuất bản',
    'Published' => 'Đã xuất bản',
    'Re-crop image' => 'Cắt lại ảnh',
    'Save as draft' => 'Lưu dạng nháp',
    'Screenshots' => 'Chụp màn hình',
    'Slug' => 'Slug',
    'Source Code' => 'Mã nguồn',
    'Source URL' => 'Đường dẫn mã nguồn',
    'Status' => 'Trạng thái',
    'Tag ID' => 'ID Thẻ',
    'Tags' => 'Thẻ',
    'The project has been moved to draft.' => 'Dự án được di chuyển vào mục nháp.',
    'Title' => 'Tiêu đề',
    'Top {n}' => 'Top {n}',
    'Top {n} projects is still empty' => 'Top {n} dự án đang là rỗng',
    'URL' => 'URL',
    'Unknown' => 'Không rõ',
    'Update' => 'Cập nhật',
    'Update project {title}' => 'Cập nhật dự án {title}',
    'Updated At' => 'Cập nhật lúc',
    'Updated By' => 'Cập nhật bởi',
    'Updated: ' => 'Được cập nhật:',
    'Upload' => 'Tải lên',
    'Upload an image' => 'Tải ảnh lên',
    'Upload screenshots' => 'Tải ảnh chụp nền',
    'User ID' => 'ID Thành viên',
    'View  {n, plural, one{one more project} other{# more projects}}' => 'Xem {n, plural, one{# проект} few{# проекта} many{# проектов} other{# dự án}}',
    'Yii Version' => 'Phiên bản Yii',
    'You can not delete this project.' => 'Bạn không có quyền xóa dự án.',
    'You can not restore a deleted project.' => 'Bạn không có quyền khôi phục dự án đã xóa.',
    'You can not update this project.' => 'Bạn không có quyền cập nhật dự án.',
    'You can only delete a project from a draft.' => 'Bạn chỉ được xóa dự án từ bộ nhớ tạm.',
    'You can upload up to 5 images. The first image will be used as a main preview of your project, while others will be displayed on the project details page' => 'Bạn chỉ được tải lên tới 5 ảnh. Ảnh đầu tiên sẽ được dùng ảnh thumbnail ở trang danh sách, ảnh khác sẽ được hiển thị ở trang chi tiết.',
    'You have no bookmarked projects yet.' => 'Bạn chưa được ưa thích dự án.',
    '{n, plural, one{# project} other{# projects}} made with {link}' => '{n,plural,one{# проект сделан} few{# проекта сделано} many{# dự án hoàn thành} other{# dự án hoàn thành}} bởi {link}',
    'You did not save the image. Are you sure you want to continue?' => 'Bạn chưa lưu ảnh. Bạn có muốn tiếp tục thực hiện?',
];
