<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update user {username}: ' => 'Cập nhật thành viên {username}:',
    'Active' => 'Kích hoạt',
    'Are you sure you want to delete this item?' => 'Xác nhận xóa?',
    'Auth Key' => 'Khóa xác thực',
    'Avatar' => 'Ảnh avatar',
    'Can not save your profile.' => ' Không thể lưu hồ sơ của bạn.',
    'Connect with {servicename}' => 'Liên kết với {servicename}',
    'Create' => 'Tạo',
    'Created At' => 'Đã tạo lúc',
    'Current avatar' => 'Ảnh avatar',
    'Delete' => 'Xóa',
    'Email' => 'Email',
    'Facebook' => 'Facebook',
    'Fullname' => 'Tên đầy đủ',
    'Github' => 'Github',
    'Haven\'t added any projects yet.' => 'Bạn chưa có dự án.',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Sai thông tin tên đăng nhập hoặc mật khẩu.',
    'Manage users' => 'Quản lý thành viên',
    'Password Hash' => 'Mã hash mật khẩu',
    'Password Reset Token' => 'Mã token khôi phục mật khẩu',
    'Status' => 'Trạng thái',
    'Twitter' => 'Twitter',
    'Update' => 'Cập nhật',
    'Updated At' => 'Cập nhật lúc',
    'Username' => 'Tên đăng nhập',
    'Users' => 'Thành viên',
    'You can not update this user.' => 'Bạn không có quyền cập nhật thành viên.',
    'Your profile has been successfully updated.' => 'Hồ sơ cập nhật thành công.',
    'Notify about new comments by e-mail' => 'Nhận thông báo bình luận mới qua e-mail',
];
