<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Explore projects' => 'Wszystkie projekty',
    'Logout' => 'Wyloguj',
    'About' => 'O projekcie',
    'Bookmarks' => 'Zakładki',
    'Don\'t have an account? {signUpLink}' => 'Nie masz konta? {signUpLink}',
    'Email' => 'Email',
    'If you forgot your password you can {reset_it}.' => 'Jeśli zapomniałeś hasła, możesz je {reset_it}.',
    'Linked {client} account.' => 'Powiązane konto {client}.',
    'Login' => 'Logowanie',
    'Password' => 'Hasło',
    'Please choose your new password:' => 'Podaj swoje nowe hasło:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Podaj swój adres email. Wyślemy na niego link resetujący hasło.',
    'RSS feed' => 'RSS',
    'Request password reset' => 'Zresetuj swoje hasło',
    'Reset password' => 'Resetowanie hasła',
    'Save' => 'Zapisz',
    'Send' => 'Wyślij',
    'Sign in with {service}' => 'Zaloguj się przez {service}',
    'Sign up!' => 'Zarejestruj się!',
    'Signup' => 'Rejestracja',
    'Social network {client} has been successfully disabled.' => 'Klient {client} został prawidłowo odłączony.',
    'This email address has already been taken.' => 'Ten adres email jest już w użyciu.',
    'This username has already been taken.' => 'Ta nazwa użytkownika jest już w użyciu.',
    'Unable to link {client} account. There is another user using it.' => 'Nie można podłączyć konta {client}. Używa go już inny użytkownik.',
    'Unable to link {client} account: {errors}' => 'Nie można podłączyć konta {client}: {errors}',
    'Unable to save user: {errors}' => 'Nie można zapisać użytkownika: {errors}',
    'Unable to save {client} account: {errors}' => 'Nie można zapisać konta {client}: {errors}',
    'Unknown' => 'Nieznany',
    'User name' => 'Nazwa użytkownika',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Użytkownik o takim samym adresie email jak na koncie {client} już istnieje, ale nie jest z nim powiązany. Zaloguj się używając tego adresu, aby powiązać konta.',
    'Username' => 'Nazwa użytkownika',
    'or' => 'lub',
    'reset it' => 'zresetować',
];
