<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Any Status' => '',
    'Are you sure you want to delete this project?' => '',
    'Delete' => '',
    'Failed to delete project.' => '',
    'Failed to update project.' => '',
    'Project deleted.' => '',
    'The project has been moved to draft.' => '',
    'You can not delete this project.' => '',
    'You can not restore a deleted project.' => '',
    'You can only delete a project from a draft.' => '',
    'Add project' => 'Dodaj projekt',
    'After the image upload, you will be able to crop it.' => 'Po załadowaniu obrazu, będziesz mógł go przyciąć.',
    'Any Yii version' => 'Wersja Yii',
    'Any code access' => 'Dostępność kodu',
    'Apply' => 'Zastosuj',
    'Approve' => 'Zatwierdź',
    'Are you sure you want to delete this image?' => 'Czy na pewno chcesz usunąć ten obraz?',
    'Back' => 'Powrót',
    'Cancel' => 'Anuluj',
    'Content' => 'Opis',
    'Created At' => 'Dodano',
    'Created By' => 'Autor',
    'Delete image' => 'Usuń obraz',
    'Deleted' => 'Usunięty',
    'Description in {language}' => 'Opis w języku {language, select, Polski{polskim} other{{language}}}',
    'Draft' => 'Szkic',
    'Featured projects' => 'Wybrane projekty',
    'Filters' => 'Filtry',
    'General' => 'Ogólne informacje',
    'General info' => 'Ogólne informacje',
    'ID' => 'ID',
    'Is Featured' => 'Wybór redakcji',
    'Is OpenSource' => 'OpenSource',
    'Language' => 'Język',
    'Made one? Share it!' => 'Stworzyłeś projekt? Pochwal się!',
    'Manage projects' => 'Zarządzaj projektami',
    'Mark as primary image' => 'Oznacz jako główny obraz',
    'New projects' => 'Nowe projekty',
    'Next' => 'Następny',
    'Not open source' => 'Kod niedostępny',
    'Only Featured' => 'Tylko wybór redakcji',
    'Open source' => 'Kod ogólnie dostępny',
    'OpenSource' => 'Kod ogólnie dostępny',
    'Please, upload some screenshots to make your project look nice.' => 'Dodaj kilka obrazów projektu, aby lepiej się prezentował.',
    'Preview & Approve' => 'Zobacz podgląd i zaakceptuj',
    'Primary image' => 'Główny obraz',
    'Project ID' => 'ID projektu',
    'Project added!' => 'Projekt dodany!',
    'Projects' => 'Projekty',
    'Projects built with Yii' => 'Projekty zbudowane na Yii',
    'Publish' => 'Opublikuj',
    'Published' => 'Opublikowane',
    'Re-crop image' => 'Skadruj obraz ponownie',
    'Save as draft' => 'Zapisz jako szkic',
    'Screenshots' => 'Obrazy',
    'Slug' => 'Slug',
    'Source Code' => 'Kod źródłowy',
    'Source URL' => 'Kod źródłowy',
    'Status' => 'Status',
    'Tag ID' => 'ID tagu',
    'Tags' => 'Tagi',
    'Title' => 'Tytuł',
    'Top {n}' => 'Top {n}',
    'Top {n} projects is still empty' => 'Top {n} projektów jest wciąż puste',
    'URL' => 'URL',
    'Unknown' => 'Nieznany',
    'Update' => 'Aktualizuj',
    'Update project {title}' => 'Aktualizuj projekt {title}',
    'Updated At' => 'Aktualizowano',
    'Updated By' => 'Aktualizował',
    'Updated: ' => 'Aktualizowany:',
    'Upload' => 'Wyślij',
    'Upload an image' => 'Wyślij obraz',
    'Upload screenshots' => 'Wyślij obrazy',
    'User ID' => 'ID użytkownika',
    'View  {n, plural, one{one more project} other{# more projects}}' => 'Zobacz {n, plural, one{jeszcze jeden projekt} few{# następne projekty} many{# kolejnych projektów} other{# projektów}}',
    'Yii Version' => 'Wersja Yii',
    'You can not update this project.' => 'Nie możesz aktualizować tego projektu.',
    'You can upload up to 5 images. The first image will be used as a main preview of your project, while others will be displayed on the project details page' => 'Możesz wysłać do 5 obrazów. Pierwszy będzie użyty jako wizytówka Twojego projektu, a pozostałe wyświetlone w jego szczegółach',
    'You have no bookmarked projects yet.' => 'Nie masz jeszcze żadnych projektów w zakładkach.',
    '{n, plural, one{# project} other{# projects}} made with {link}' => '{n,plural,one{# projekt} few{# projekty} many{# projektów} other{# projektów}} zbudowanych na {link}',
];
