<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Connect with {servicename}' => 'Połącz z kontem {servicename}',
    'Active' => 'Aktywny',
    'Are you sure you want to delete this item?' => 'Czy na pewno chcesz usunąć ten element?',
    'Auth Key' => 'Klucz autoryzacyjny',
    'Create' => 'Stwórz',
    'Created At' => 'Dodano',
    'Delete' => 'Usuń',
    'Email' => 'Email',
    'Facebook' => 'Facebook',
    'Fullname' => 'Pełne imię i nazwisko',
    'Github' => 'Github',
    'Haven\'t added any projects yet.' => 'Nie dodał jeszcze żadnych projektów.',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Nieprawidłowa nazwa użytkownika lub hasło.',
    'Manage users' => 'Zarządzaj użytkownikami',
    'Password Hash' => 'Hasz hasła',
    'Password Reset Token' => 'Token resetujący hasło',
    'Status' => 'Status',
    'Twitter' => 'Twitter',
    'Update' => 'Aktualizuj',
    'Update {modelClass}: ' => 'Aktualizuj {modelClass}: ',
    'Updated At' => 'Aktualizowano',
    'Username' => 'Nazwa',
    'Users' => 'Użytkownicy',
];
